repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.17  # Replace with the desired version
    hooks:
      - id: uv-lock
  - repo: local
    hooks:
      - id: strip-widgets
        name: Strip widget metadata from notebooks
        entry: .pre-commit-hooks/strip_widgets.py
        language: python
        additional_dependencies: [nbformat]
        files: \.ipynb$