[project]
name = "bigquery-hackathon"
version = "0.1.0"
description = "Ecommerce Recommendation with bigquery and python"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nbformat>=5.10.4",
    "pre-commit>=4.3.0",
]
